
# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

# please do not edit this file
# please do not edit this file

import sys
import random
import pickle
import time
import os 
onestats = 1
loadingtime = 3 #to insure python is loaded.
load_stats = 0
class game:
    pass
class doggos(game):
    pass
def start():
    print('ProjectDoggo')
    print('made by')
    print('qwertydev1')
    print('please open as fullscreen.')
    print('loading...')
    time.sleep(loadingtime)
    print('loaded!')
    print('ProjectDoggo')
    optionStats = input('Choose an option: 1(load) or 2(new)')
    if optionStats == '1':
        print('save is not ready yet')
    elif optionStats == '2':
        load_stats = '0'
        if load_stats == '0':
            name = input('What would You Like to be called?')
            print('welcome, %s' % name)
            options = input('''1 - Play
2 - How to Play''')
            
        else:
            print('that is not valid')
print('welcome to ProjectDoggo! type start() to start.')
